development:
  maps_key: ABQIAAAA4TpmzwXT7dCXvHE7g1lTshTJQa0g3IQ9GZqIMmInSLzwtGDKaBTSWr7WjZBg--GV5IPls6kZAYF1cA

production:
  maps_key: ABQIAAAA4TpmzwXT7dCXvHE7g1lTshTX-hzK5gZjK5_S3eSa8P2panGzAhQ_2ztSC3gG6eh-ddx1wWcqXbMi2w
